{* This is the default view of an DFP eZ Flow block, do not edit this file, create an override instead *} 
{def $id = concat($block.view,'_',$block.id)}

<!-- all2e Google dfp: {$block.view} START -->
<div class="ads_content" id="{$id}">
    {all2edfp_require($block.view,$id)}
</div>
<!-- all2e Google dfp: {$block.view} END -->