{* This is the default view of an DFP flow block, do not edit this file, create an override instead *} 
{def $id = concat($block.view,'_',$block.id)}

<div class="block-type-all2edfp block-view-{$block.view}">
<div class="attribute-header"><h2>{$block.name}</h2></div>
<div class="ads_content" id="{$id}">
    {all2edfp_require($block.view,$id)}
</div>
</div>

